### PR TITLE
Multiple Decimal Points Bug fixed

### PR DESCRIPTION
**Pull request by Archfx**
The initial decimal point will be considered as the correct decimal point. Others will get ignored.

Initial decimal point issue corrected
Previously .41 gets recognized as 41.It is corrected to 0.41

### CODE REVIEW

**Comment by Alii-Khaled** [comment]
This Solves the issue in GUI Visma only while it is not working correctly in CLI too, also we should refuse any type of input like that from the root, do you understand my view ?!

**Comment by Archfx** [comment]
> This Solves the issue in GUI Visma only while it is not working correctly in CLI too, also we should refuse any type of input like that from the root, do you understand my view ?!

Yes, I understand.
I will look in to CLI

**Comment by Archfx** [comment]
Travis CI build failed due to a issue in pylama. can we change the travis.yml

**Comment by PulkitMishra** [comment]
@Archfx all PRs are to be made in the Dev branch

**Comment by abhishekti7** [comment]
@Archfx pylama errors can be fixed. You have some syntactical errors. refer to the travis build and fix those errors.

**Comment by Archfx** [comment]
> @Archfx all PRs are to be made in the Dev branch

I have changed the base branch to dev

**Comment by PulkitMishra** [comment]
Nice. I saw. Would have been better if you updated this PR itself. Never mind.
Close this one for now and we can edit #167

**Comment by Archfx** [comment]
> Nice. I saw. Would have been better if you updated this PR itself. Never mind.
> Close this one for now and we can edit #167

😃

**Pull request closed without merging**
