### PR TITLE
update run.sh

### LINKED ISSUE #34: sudo pip install pyopengl not working

### PR DESCRIPTION
**Pull request by pranavvardia**
update .gitignore
Fixes #34

### CODE REVIEW

**Comment by sidkothiyal** [comment]
@supragya  @pranavvardia 
Hi guys,
I merged your respective commits. Do you mind testing them on your distros and see if they work fine?

**Comment by supragya** [comment]
Hi Sid,
PR submitted by me was tested fine on Manjaro and hence arch distributions.
Can you explain what do you expect of VISMA this year?

Regards
Supragya Raj

On 04-Mar-2018 03:13, "Siddharth Kothiyal" <notifications@github.com> wrote:

@supragya <https://github.com/supragya> @pranavvardia
<https://github.com/pranavvardia>
Hi guys,
I merged your respective commits. Do you mind testing them on your distros
and see if they work fine?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aerospaceresearch/VisMa/pull/35#issuecomment-370182181>,
or mute the thread

**Comment by sidkothiyal** [comment]
@supragya great!
Sure, just give me time till tomorrow morning, I am writing a mail in which I will try to explain everything in detail, we can have a detailed discussion after that.

**Comment by pranavvardia** [comment]
@sidkothiyal the code runs fine on Debian. I also plan on extending the functionality to macOS

**Comment by pranavvardia** [comment]
I think my PR has not been merged because there's no gitignore file in the repo

**Pull request merged**
