### PR TITLE
Fixed an error in transposeMat() which previously only worked for square matrices.

### PR DESCRIPTION
**Pull request by AbishekSeshan**
Added a test case in test_matrix.py regarding the same.

@8hantanu Please review.

### CODE REVIEW

**Comment by AbishekSeshan** [comment]
@8hantanu Can you please tell me how do I keep updating my forked repo with the original aerospaceresearch/visma dev repo? In my forked repo it says that my fork is 19 commits ahead and 1 commit behind. I tried many options but all in vain.
2. Can you please add the link for zulip chat for Visma where I can post my doubts instead of here? 
Thank you!
edit: now my fork is 20 commits ahead.

**Comment by mayankDhiman** [comment]
> @8hantanu Can you please tell me how do I keep updating my forked repo with the original aerospaceresearch/visma dev repo? In my forked repo it says that my fork is 19 commits ahead and 1 commit behind. I tried many options but all in vain.
> 2. Can you please add the link for zulip chat for Visma where I can post my doubts instead of here?
> Thank you!
> edit: now my fork is 20 commits ahead.

I prefer this workflow:
1. `git fetch upstream` where you set upstream as a remote to origin visma repo.
2. `git reset --hard dev` this makes your local clone equal to dev of upstream. 
3. `git push origin dev` this makes your fork equal to original repo.
For more details refer git documentation.
`git merge dev` also works in second step. `git reset` is less preferred since it will not consider your local commits.
Hope that helps.

**Comment by AbishekSeshan** [comment]
@mayankDhiman thanks man!

**Comment by 8hantanu** [comment]
> 2. Can you please add the link for zulip chat for Visma where I can post my doubts instead of here?

Zulip chat: https://aerospaceresearch.zulipchat.com/
For visma related: https://aerospaceresearch.zulipchat.com/#narrow/stream/181873-visma

**Review by 8hantanu — APPROVED** [review]

**Pull request merged**
